import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Menuka Deshan',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <meta name="google-site-verification" content="6grk_64Pgwehy4e7vjtpGFNASVAgZQN4ZEPPOdnTDdA" />
      <body className={inter.className}>
      <Navbar/>
      {children}
      </body>
    </html>
  )
}
